name = "discord-auth-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
DISCORD_CLIENT_ID = "1518260560766963912"
DISCORD_REDIRECT_URI = "https://discord-auth-worker.arianthonyungsod.workers.dev/discord-callback"
DISCORD_GUILD_ID = "1405710246655164557"
TARGET_ORIGIN = "https://momowzen.github.io/STR.BossTracker"
ADMIN_USERS = "tadatoki,jhayez_,bhabylainel9010,drindrin9466,mariaerica_16,jammers929,nemesissss,zer0wind,zerochill0618"
